Fix error with setuptools
fatal: [staging_01]: FAILED! => changed=false
  cmd:
  - /usr/lib/ckan/default/bin/pip3
  - install
  - -e
  - git+https://github.com/ckan/ckanext-spatial.git@v2.1.1#egg=ckanext-spatial
  msg: |-
    stdout: Obtaining ckanext-spatial from git+https://github.com/ckan/ckanext-spatial.git@v2.1.1#egg=ckanext-spatial
      Cloning https://github.com/ckan/ckanext-spatial.git (to revision v2.1.1) to /usr/lib/ckan/default/src/ckanext-spatial
      Resolved https://github.com/ckan/ckanext-spatial.git to commit 938308469892e4bcf7389cb4adee5ccdd5a0ccca
      Preparing metadata (setup.py): started
      Preparing metadata (setup.py): finished with status 'error'

    :stderr:   Running command git clone --filter=blob:none --quiet https://github.com/ckan/ckanext-spatial.git /usr/lib/ckan/default/src/ckanext-spatial
      Running command git checkout -q 938308469892e4bcf7389cb4adee5ccdd5a0ccca
      Running command git submodule update --init --recursive -q
      error: subprocess-exited-with-error

      × python setup.py egg_info did not run successfully.
      │ exit code: 1
      ╰─> [6 lines of output]
          Traceback (most recent call last):
            File "<string>", line 2, in <module>
            File "<pip-setuptools-caller>", line 34, in <module>
            File "/usr/lib/ckan/default/src/ckanext-spatial/setup.py", line 2, in <module>
              from ckanext.spatial import __version__
          ModuleNotFoundError: No module named 'ckanext.spatial'
          [end of output]

      note: This error originates from a subprocess, and is likely not a problem with pip.
    error: metadata-generation-failed

    × Encountered error while generating package metadata.
    ╰─> See above for output.

    note: This is an issue with the package mentioned above, not pip.
    hint: See above for details.

https://github.com/ckan/ckanext-spatial/issues/333